{% set name = "scalapackfx" %}
{% set version = "1.0.2" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 842908c0ae46f1d669c5cb1a4123cfdf8749e29d7249aa589107c5163c29f0fc

build:
  number: {{ build }}
  skip: true  # [win]

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}
    - scalapack
    - libblas
    - liblapack
  run:
    - {{ mpi }}
    - scalapack


test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/libscalapackfx.dylib  # [osx]
    - test -f $PREFIX/lib/libscalapackfx.so  # [linux]

about:
  home: https://github.com/dftbplus/{{ name }}
  license: BSD-2-Clause
  license_file:
    - LICENSE
  summary: Modern Fortran wrappers around ScaLAPACK routines

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
