{% set name = "scalapackfx" %}
{% set version = "1.1" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 29ffa0fefa6fbfc2e36e55ab08b1a4b2093a3ea3ffa0283208dde3b4a65988c1

build:
  number: {{ build }}
  skip: true  # [win]

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}
    - scalapack
    - libblas
    - liblapack
  run:
    - {{ mpi }}
    - scalapack


test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --modversion
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}

about:
  home: https://github.com/dftbplus/{{ name }}
  license: BSD-2-Clause
  license_file:
    - LICENSE
  summary: Modern Fortran wrappers around ScaLAPACK routines

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
